### ISSUE TITLE
StateManagementBot.cs [!code-csharpOnTurnAsync]

### ISSUE THREAD

**Issue by SugarGuan** [MicrosoftDocs/bot-docs.zh-cn#3]
页面里的代码示例没有加载。
The code sample in the page is not loaded

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: e18bc52f-7eaf-a473-1cba-9b7c83bd0025
* Version Independent ID: c1b6cf03-c236-cfbf-aa4b-96961b816bc3
* Content: [保存用户和聊天数据 - Bot Service](https://docs.microsoft.com/zh-cn/azure/bot-service/bot-builder-howto-v4-state?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-state.md](https://github.com/MicrosoftDocs/bot-docs.zh-cn/blob/live/articles/v4sdk/bot-builder-howto-v4-state.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by CeciAc** [comment]
Hello, @SugarGuan 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @SugarGuan 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/bot-docs/issues/1191

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
@ishasahni1 the error was fixed in the source pages and will be fixed in the localized pages after translation

**Comment by CeciAc** [comment]
Hello, @SugarGuan
Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages XXX. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
