### ISSUE TITLE
The symbols are wrongly rendered.

### ISSUE THREAD

**Issue by yanxiaodi** [MicrosoftDocs/bot-docs.zh-cn#4]
All the symbols on this page cannot be shown correctly.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 60950444-cdcc-f0b9-aa21-c99894e26b50
* Version Independent ID: 0bd14221-e030-f9d8-41e6-1a52c9a76440
* Content: [通道参考 - Bot Service](https://docs.microsoft.com/zh-cn/azure/bot-service/bot-service-channels-reference?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-channels-reference.md](https://github.com/MicrosoftDocs/bot-docs.zh-cn/blob/live/articles/bot-service-channels-reference.md)
* Service: **bot-service**
* Sub-service: **tools**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by CeciAc** [comment]
Hello, @yanxiaodi 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
@ishasahni1 can you please check this issue?
It looks like this box shouldn't be localized, the en-us version looks fine but it breaks when localized.

**Comment by ishasahni1** [comment]
@CeciAc we are going to work with engineering on addressing this issue.

**Comment by CeciAc** [comment]
Hi @ishasahni1 
Is there any updates on this?

**Comment by ishasahni1** [comment]
@CeciAc This issue is going to be fixed by next Monday at latest. The fix has been made by engineering and will be deployed by Monday morning.

**Comment by ishasahni1** [comment]
@yanxiaodi thank you so much for the feedback and for all your patience. I would like to inform you that this issue has now been resolved.

@CeciAc FYI
